### ISSUE TITLE
Fixes for compiling on linux

### ISSUE THREAD

**Issue by tryggvit** [NOVACProject/NovacPPP#7]
I needed to make some minor fixes to compile the code on linux, which I am attaching as patchfiles.

[patches.zip](https://github.com/NOVACProject/NovacPPP/files/3177788/patches.zip)

NOVACPPP/SpectralEvaluation

- Added x-privilege-to-Build_UnixMake.sh
- Fixed case-sensitive error for "GPSData" in makefile

NOVACPPP

- Added missing includes
- Fixed m_specNum bug

Ubuntu 18.04.1 LTS
Linux version 4.15.0-47-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))

**Comment by mattias42** [comment]
patches applied, missed to close issue.
